# Numpy
   - strand for Numerical Python, its a core scientific computing Library, provide multidimensional array. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
https://numpy.org/doc/stable/index.html

In [1]:
import numpy as np            # alias np here for numpy

In [2]:
# cheching numpy Version
np.__version__

'1.20.3'

#### Main function to create array is - np.array()
- numpy used to work with arrays. the array object in numpy is called ndarray.create a numpy ndarray object by using the array() 

### - Dimensions in Arrays                                         ( very Importent )
 - A dimension in array is one level of array depth(nested array).
 - Nested array : are arrays that have arrays as their elemnts
 - only [] brackets are use to make 1,2,n dimentional array  with np.array([[]])-in paranthesis use brackets

# 0 dimensional array  
- not much used 
- 0-D arrays or Scalars, are the elements in an array, 
- each value in an array is a 0-D array

- Single item in paranthesis without square[]brackets or
- but with round()prantheses and curly{}braces can't make multidimensional array

In [3]:
a=np.array(42)  # single item in paranthesis without square[]brackets
print(a),a.ndim

42


(None, 0)

In [4]:
a=np.array(42)                     # 0d
b=np.array([42])                   # 1d 
c=np.array(((43)))                 # 0d 
a,b,c,a.ndim,b.ndim,c.ndim

(array(42), array([42]), array(43), 0, 1, 0)

# 1 dimensional array
## 1d = [0d,0d,0d]         - ( in 1d has one, two and more set of elements\0 d in square Bracket )
#### np.arange()
- methods
- np.array(), np.zeros(), np.ones(), np.empty(), 
- np.arange(), np.linspace(), dtype()

In [5]:
# heterogeneous
hetero=np.array([11,'om',True])
print('heterogeous-',hetero)
# homogeneous
homo=np.array([11,22,33,44])
print('homogenous-',homo)

heterogeous- ['11' 'om' 'True']
homogenous- [11 22 33 44]


### Create array with list, tuple, dictionary, set , string with different data types

###### Method 1 - in np.array(variable)

In [6]:
# create array with list, tuple, dictionary, set , string with different data types
list_arr=[1,22,33,11,43,56,4]
tuple_arr=(1,3,4455,8,65,4,24) 
set_arr= {22,33,44,55,66,2,9}
dict_arr={1:100,2:200,3:'IBM'}
str_arr='np','numpy', 'pandas', 'matplotlib', 'seaborn'

In [7]:
l_a=np.array(list_arr)
print('list_a',l_a)
l_a

list_a [ 1 22 33 11 43 56  4]


array([ 1, 22, 33, 11, 43, 56,  4])

In [8]:
t_a=np.array(tuple_arr)
print('tuple_a',t_a)
t_a

tuple_a [   1    3 4455    8   65    4   24]


array([   1,    3, 4455,    8,   65,    4,   24])

In [9]:
s_t=np.array(set_arr)
print('set_a',s_t)
s_t

set_a {33, 66, 2, 22, 55, 9, 44}


array({33, 66, 2, 22, 55, 9, 44}, dtype=object)

In [10]:
d_t=np.array(dict_arr)
print('dict_a',d_t)
d_t

dict_a {1: 100, 2: 200, 3: 'IBM'}


array({1: 100, 2: 200, 3: 'IBM'}, dtype=object)

In [11]:
s_t=np.array(str_arr)
print('string_a',s_t)
s_t

string_a ['np' 'numpy' 'pandas' 'matplotlib' 'seaborn']


array(['np', 'numpy', 'pandas', 'matplotlib', 'seaborn'], dtype='<U10')

###### Method 2 - np.array({([value1,value2,value3])})  -
- direct create str,dict,list,set,tuple inside () of np.array

In [12]:
# create array with list, tuple, dictionary, set , string with different data types
list_arr=np.array([1,22,33,11,43,56,4])
tuple_arr=np.array((1,3,4455,8,65,4,24))
set_arr=np.array({22,33,44,55,66,2,9})
dict_arr=np.array({1:100,2:200,3:'IBM'})
str_arr=np.array(('np','numpy', 'pandas', 'matplotlib', 'seaborn'))  
list_arr,tuple_arr,set_arr,dict_arr,str_arr

(array([ 1, 22, 33, 11, 43, 56,  4]),
 array([   1,    3, 4455,    8,   65,    4,   24]),
 array({33, 66, 2, 22, 55, 9, 44}, dtype=object),
 array({1: 100, 2: 200, 3: 'IBM'}, dtype=object),
 array(['np', 'numpy', 'pandas', 'matplotlib', 'seaborn'], dtype='<U10'))

# Check array's dimension, type, datatype, size, shape
- v.ndim, type(v),v.dtype,  v.size, v.shape 

In [13]:
l=[1,22,33,11,43,56,4]
print('list-',l, type(l))
print('--------------------------------------------')
arr_1d=np.array([1,22,33,11,43,56,4])
print('array-',arr_1d,',dimension-',arr_1d.ndim,',type-',type(arr_1d))
print('dtype-',arr_1d.dtype,'Size-',arr_1d.size,'shape-',arr_1d.shape)

list- [1, 22, 33, 11, 43, 56, 4] <class 'list'>
--------------------------------------------
array- [ 1 22 33 11 43 56  4] ,dimension- 1 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 7 shape- (7,)


https://www.geeksforgeeks.org/data-type-object-dtype-numpy-python/

- defference bitween list and array 
- Memory Management - fast processing in mathematical calculations, less time comsumming, developed in c++ language

In [14]:
# import sys - get size of, 
l=[1,22,33,11,43,56,4]
arr=np.array([1,22,33,11,43,56,4],dtype='int64')
print('type(list)-',type(l))
print('type(array)-',type(arr))
print(l)
print(arr)
import sys
print('list size in  bytes-',sys.getsizeof(1)*len(l))     
print('array size in bytes-',sys.getsizeof(arr))     # bytes
print(arr.itemsize)
print(arr.size)
print(len(arr))
print(arr.itemsize*arr.size)    # bytes
aaa=arr.tolist()
aaa

type(list)- <class 'list'>
type(array)- <class 'numpy.ndarray'>
[1, 22, 33, 11, 43, 56, 4]
[ 1 22 33 11 43 56  4]
list size in  bytes- 196
array size in bytes- 160
8
7
7
56


[1, 22, 33, 11, 43, 56, 4]

# 2 dimensional array 
## 2d = [1d,1d,1d]         - ( in 2d has one, two and more set of elements\1 d in square Bracket )

#### np.arange()


In [15]:
z=np.array([[]])
print(z.ndim)

2


In [16]:
l=[[1,2,233,44,55],[33,44,55,22,11]]
arr_2d=np.array([[1,2,233,44,55],[33,44,55,22,11]])
l,arr_2d

([[1, 2, 233, 44, 55], [33, 44, 55, 22, 11]],
 array([[  1,   2, 233,  44,  55],
        [ 33,  44,  55,  22,  11]]))

### v.ndim, type(v),v.dtype,  v.size, v.shape - 2D

In [17]:
print('dimension-',arr_2d.ndim,',type-',type(arr_2d))
print('dtype-',arr_2d.dtype,'Size-',arr_2d.size,'shape-',arr_2d.shape)

dimension- 2 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 10 shape- (2, 5)


# 3 dimensional array 
## 3d = [2d,2d,2d]         - ( in 3d has one, two and more set of elements\2 d in square Bracket )
#### np.arange()

In [18]:
arr_3d=np.array([[[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]]])
arr_3d

array([[[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]]])

In [19]:
print('dimension-',arr_3d.ndim,',type-',type(arr_3d))
print('dtype-',arr_3d.dtype,'Size-',arr_3d.size,'shape-',arr_3d.shape)

dimension- 3 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 48 shape- (6, 2, 4)


# 4 dimensional array 
## 4d = [3d,3d,3d]         - ( in 4d has two or more set of 3 d )
#### np.arange()

In [20]:
arr_4d=np.array([[[[1,22,3,3],[4,5,6,7]],[[1,22,3,3],[4,5,6,7]]],         
                [[[1,22,3,3],[4,5,6,7]],[[1,22,3,3],[4,5,6,7]]],
                [[[1,22,3,3],[4,5,6,7]],[[1,22,3,3],[4,5,6,7]]],
                [[[1,22,3,3],[4,5,6,7]],[[1,22,3,3],[4,5,6,7]]]])
arr_4d

array([[[[ 1, 22,  3,  3],
         [ 4,  5,  6,  7]],

        [[ 1, 22,  3,  3],
         [ 4,  5,  6,  7]]],


       [[[ 1, 22,  3,  3],
         [ 4,  5,  6,  7]],

        [[ 1, 22,  3,  3],
         [ 4,  5,  6,  7]]],


       [[[ 1, 22,  3,  3],
         [ 4,  5,  6,  7]],

        [[ 1, 22,  3,  3],
         [ 4,  5,  6,  7]]],


       [[[ 1, 22,  3,  3],
         [ 4,  5,  6,  7]],

        [[ 1, 22,  3,  3],
         [ 4,  5,  6,  7]]]])

In [21]:
print('dimension-',arr_4d.ndim,',type-',type(arr_4d))
print('dtype-',arr_4d.dtype,'Size-',arr_4d.size,'shape-',arr_4d.shape)

dimension- 4 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 64 shape- (4, 2, 2, 4)


https://www.nature.com/articles/s41586-020-2649-2

# 5 dimensional array 
## 5d = [4d,4d,4d]         - ( in 5d has two or more set of 4 d )
#### np.arange()

In [22]:
arr_5d=np.array([[         
                  [[[1,22,3,3],[4,5,6,7]],[[1,22,3,3],[4,5,6,7]]]],
                 [     
                  [[[1,22,3,3],[4,5,6,7]],[[1,22,3,3],[4,5,6,7]]]]])
arr_5d

array([[[[[ 1, 22,  3,  3],
          [ 4,  5,  6,  7]],

         [[ 1, 22,  3,  3],
          [ 4,  5,  6,  7]]]],



       [[[[ 1, 22,  3,  3],
          [ 4,  5,  6,  7]],

         [[ 1, 22,  3,  3],
          [ 4,  5,  6,  7]]]]])

In [23]:
print('dimension-',arr_5d.ndim,',type-',type(arr_5d))
print('dtype-',arr_5d.dtype,'Size-',arr_5d.size,'shape-',arr_5d.shape)

dimension- 5 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 32 shape- (2, 1, 2, 2, 4)


# High dimensional array
- an array can have any number of demensions.
- when the array is created, you can define the no. of dimensions by using the ndmin argument.


In [24]:
arr_6d=np.array([1,2,3],ndmin=6)
print(arr_6d)
print('number of Dimensions:',arr_6d.ndim)

[[[[[[1 2 3]]]]]]
number of Dimensions: 6


In [25]:
print('dimension-',arr_6d.ndim,',type-',type(arr_6d))
print('dtype-',arr_6d.dtype,'Size-',arr_6d.size,'shape-',arr_6d.shape)

dimension- 6 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 3 shape- (1, 1, 1, 1, 1, 3)


# Other funtions  for creating arrays
- np.array(), np.zeros(), np.ones(), np.empty(), 
- np.arange(), np.linspace(), np.random.randint(), np.full() dtype()

In [26]:
# np.array([value1,value2,value3])   
acm1_1=np.array([11,22,3,44,55])
print('acm1_1-',acm1_1)
list_=[11,22,3,44,55]
acm1_2=np.array(list_)
print('acm1_2-',acm1_2)

acm1_1- [11 22  3 44 55]
acm1_2- [11 22  3 44 55]


In [27]:
#acm= array create methods
# np.arange(value) 
acm2_1=np.arange(6)        
print('acm2_1',acm2_1)
acm2_2=np.arange(1,10,3)    #  np.arange(value[start],value[end],value[step]) 
print('acm2_2',acm2_2)

acm2_1 [0 1 2 3 4 5]
acm2_2 [1 4 7]


In [28]:
# np.ones()
acm3=np.ones(6)
acm3

array([1., 1., 1., 1., 1., 1.])

In [29]:
# np.zeros() 
acm4=np.zeros(6)
acm4

array([0., 0., 0., 0., 0., 0.])

In [30]:
# np.empty()
acm5=np.empty(7)
acm5

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 3.05414073e-305])

In [31]:
# np.linspace()   
acm6=np.linspace(4,10 ,num=3 )  # np.linspace(start,end,num= value_ammounts)
acm6

array([ 4.,  7., 10.])

In [32]:
#np.arrange()
acm7=np.arange(1,10,2)    #  np.arange(value[start],value[end],value[step]) 
acm7

array([1, 3, 5, 7, 9])

In [33]:
# np.random.randint()
import random    # here we importing random module
acm8=np.random.randint(1,100,100)  # (value[start],value[end],value[amount])
acm8

array([68, 35, 45, 96, 86, 20, 18, 48, 46, 69, 23, 71, 56,  5,  1, 19, 35,
       40, 19, 59, 60, 57, 60, 72, 18, 96, 96, 23, 29, 59, 50, 83, 13, 17,
       91, 36, 99, 22,  2, 46, 11, 79, 45,  4, 99, 71, 25,  4, 90, 12, 73,
       80, 53, 87, 67, 10, 72, 18, 67, 35, 94, 63, 26, 71, 49, 22, 67, 53,
       18, 24, 73, 81, 72, 15, 62, 86, 94,  4, 86,  1, 50, 10, 24, 53, 85,
       63, 63, 37, 78, 42, 85, 79,  1, 78, 76,  8, 52, 48, 57, 60])

In [34]:
# np.full()
acm9=np.full((2,2,3),10) #np.full((set amt.,row,columns),ele no.) fix numpy array with fix number
acm9

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

- https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# 2 dimensional array/ 3 dimensional array / 4 dimensional array / n dimensional array

- if you want to create 2d,3d,4d with the help of these below mentioned method (like np.zeros(), np.ones() so on..) without  reshape and resize function could not be posible             (very importent)
- np.array(), np.zeros(), np.ones(), np.empty(), 
- np.arange(), np.linspace(), np.random.randint(), np.full() dtype()


# reshape & resize numpy help to create 2D,3D from 1D 
- first does factors of 1D array then use see in example 
- 100= factor - (50,2),(25,4),(20,5)
- v.reshape(rows,columns) and v.resize(rows,columns)

https://www.geeksforgeeks.org/difference-between-reshape-and-resize-method-in-numpy/#:~:text=reshape()%20and%20numpy.,directly%20changes%20the%20original%20array.

https://numpy.org/doc/stable/reference/arrays.ndarray.html

# v.ravel()

In [35]:
a=np.array([[1,2,3,4,5],[65,43,23,22,11]])
a.ravel() #  convert any dimensional array in  1d array

array([ 1,  2,  3,  4,  5, 65, 43, 23, 22, 11])

In [36]:
#np.zeros(), np.ones(), np.empty(),
#np.arange(), np.linspace(), dtype()
a_z=np.zeros(100)
a_z_reshape=a_z.reshape(2,50)
print(a_z_reshape,a_z_reshape.ndim)
print('------------------------------------------')
print(a_z,a_z.ndim)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]] 2
------------------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.] 1


In [37]:
# changes will be in implemented variable not stored in assigned variable
a_z=np.zeros(100) 
a_z_resize=a_z.resize(2,50)
print(a_z_resize) # assigned variable 
print(a_z) # function implemented variable

None
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]


In [38]:
a_z=np.zeros(100).reshape(2,2,25)
a_z,a_z.ndim

(array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.]]]),
 3)

In [39]:
'''- np.array(), np.zeros(), np.ones(), np.empty(), 
- np.arange(), np.linspace(), np.random.randint(), np.full() dtype()'''
a_o=np.ones(200).reshape(2,4,5,5)
a_o,a_o.ndim

(array([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 

In [40]:
'''- np.array(), np.zeros(), np.ones(), np.empty(), 
- np.arange(), np.linspace(), np.random.randint(), np.full() dtype()'''
a_o=np.empty(200).reshape(2,4,5,5)
a_o,a_o.ndim

(array([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 

In [41]:
np.empty(shape = [2,3], dtype = float)


array([[1., 1., 1.],
       [1., 1., 1.]])

https://www.sharpsightlabs.com/blog/numpy-empty/#numpy-empty-syntax
What does NP empty return?
empty(shape, dtype = float, order = 'C') : Return a new array of given shape and type, with random values.
https://www.geeksforgeeks.org/numpy-empty-python/

In [42]:
'''- np.array(), np.zeros(), np.ones(), np.empty(), 
- np.arange(), np.linspace(), np.random.randint(), np.full() dtype()'''
a_range=np.arange(1000).reshape(4,10,25)
a_range

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24],
        [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
          37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
          49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
          62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
          74],
        [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
          87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
          99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
         124],
        [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
         137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
         149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
         162,

In [43]:
'''- np.array(), np.zeros(), np.ones(), np.empty(), 
- np.arange(), np.linspace(), np.random.randint(), np.full() dtype()'''
a_lins=np.linspace(0,1000,10).reshape(2,5)  # np.linspace(start,end,num= value_ammounts)
a_lins,a_lins.shape

(array([[   0.        ,  111.11111111,  222.22222222,  333.33333333,
          444.44444444],
        [ 555.55555556,  666.66666667,  777.77777778,  888.88888889,
         1000.        ]]),
 (2, 5))

In [44]:
'''- np.array(), np.zeros(), np.ones(), np.empty(), 
- np.arange(), np.linspace(), np.random.randint(), np.full() dtype()'''
import random
a_rand=np.random.randint(0,1000,10).reshape(2,5)   # start, stop, amount
a_rand,a_rand.shape

(array([[159, 903, 619, 542, 301],
        [994, 330, 356, 931, 822]]),
 (2, 5))

In [45]:
'''- np.array(), np.zeros(), np.ones(), np.empty(), 
- np.arange(), np.linspace(), np.random.randint(), np.full() dtype()'''
a_full=np.full((4,2,2),10) #np.full((row,columns,dimension),ele no.) fix numpy array with fix number
a_full

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

## numpy data types
- datatypes in numpy
- numpy has some extra data types , and refer to data types with one character, like i for integers, u for unsigned integer etc.
below is a list of all data type
- i-int
- b-bool
- u-unsigned int
- f-float
- c-complex float
- m-timedelta
- M-datetime
- o- object
- S-string
- U-unicode string
- V-fixed chunk of memory for other type(void)

# Casting

- Creating data type with defined data type

In [46]:
s=np.array(['apple','banana','mango'])
s,s.dtype

(array(['apple', 'banana', 'mango'], dtype='<U6'), dtype('<U6'))

In [47]:
# creating data type with defined data type
n=np.array([1,2,3,4],dtype='S')
print(n)
print(n.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [48]:
# for i, u, f, S, U we can define size as well
a=np.array([1,0,3,4,6,5,7],dtype='i')
a

array([1, 0, 3, 4, 6, 5, 7], dtype=int32)

In [49]:
# sdt = specifying data type
sdt=np.ones(2,dtype=np.int64)
sdt

array([1, 1], dtype=int64)

In [50]:
sdt1=np.arange(10,100,10,dtype=np.int8)
sdt1

array([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=int8)

-  converting data type on existing arrays - casting
- astype()

In [51]:
# converting data type on existing arrays - casting
# astype()
# astype()
a=np.array([1.1,2.1,3.2,0])
b=a.astype('i')
c=a.astype(int)
d=a.astype(bool)
print(b)
print(c)
print(d)

[1 2 3 0]
[1 2 3 0]
[ True  True  True False]


# Indexing & Slicing  - in 1D,2D,3D, ..nD Array 

In [52]:
# 1D Indexing & slicing
a=np.array([22,32,45,65,76,45,22,32,45,65,76,45])
print(a)
print(a[3])
print(a[5])

[22 32 45 65 76 45 22 32 45 65 76 45]
65
45


In [53]:
# 1D slicing
print(a)
print(a[0:10:3])
print(a[0:13:2])

[22 32 45 65 76 45 22 32 45 65 76 45]
[22 65 22 65]
[22 45 76 22 45 76]


In [54]:
# 2d array
a=np.array([[22,32,45,65,76,45,22,32,45,65,76,45],[22,32,45,65,76,45,22,32,45,65,76,45]])
a

array([[22, 32, 45, 65, 76, 45, 22, 32, 45, 65, 76, 45],
       [22, 32, 45, 65, 76, 45, 22, 32, 45, 65, 76, 45]])

In [55]:
a.shape,a[[0,0,0,-1],[1,2,-2,-3]] 

((2, 12), array([32, 45, 76, 65]))

In [56]:
# 3d array
a=np.array([[[1,3,2,4],[4,2,4,67]],[[1,3,2,4],[4,2,4,67]]])
a.shape,a.ndim,a,

((2, 2, 4),
 3,
 array([[[ 1,  3,  2,  4],
         [ 4,  2,  4, 67]],
 
        [[ 1,  3,  2,  4],
         [ 4,  2,  4, 67]]]))

In [57]:
# advance indexing in 3d
a[[1],[1,0,0],[0,1,3]]

array([4, 3, 4])

In [58]:
# advance slicing in 3d
a,a[1][::,:3]

(array([[[ 1,  3,  2,  4],
         [ 4,  2,  4, 67]],
 
        [[ 1,  3,  2,  4],
         [ 4,  2,  4, 67]]]),
 array([[1, 3, 2],
        [4, 2, 4]]))

# nD

In [59]:
import random
a=np.random.randint(0,1000,100).reshape(2,2,5,5)       # start,stop,amount
a

array([[[[201, 990, 702, 368, 249],
         [274,  67, 767, 540, 176],
         [174, 828, 712, 931, 337],
         [ 73, 555, 654, 741, 694],
         [ 40, 333, 964, 114, 428]],

        [[775, 521, 292, 625, 600],
         [802, 438, 759, 724, 244],
         [731, 179, 143, 410, 183],
         [866, 390, 214, 562, 506],
         [285, 865, 794, 148, 462]]],


       [[[973, 879, 410, 314, 609],
         [306, 962, 574, 528, 438],
         [531, 627, 236, 813, 320],
         [ 14,  30,  37, 738, 362],
         [985,  25, 910, 662, 512]],

        [[764,   8, 814, 513, 920],
         [754, 310, 189, 720, 666],
         [102, 945, 840, 482, 189],
         [503, 652, 720, 808, 974],
         [647, 265, 496, 334, 811]]]])

# Advance Indexing 

In [60]:
a[[1],[1],[2],[3]]                # variable[set1],[subset1],[row],[column]

array([482])

In [61]:
a[[0],[1],[2,1,0],[2,0,1]]       # variable[set0],[subset1],[rows],[columns]

array([143, 802, 521])

In [62]:
a[[1],[1],[0,1,3,2,4],[1,2,3,3,4]]

array([  8, 189, 808, 482, 811])

# Advance Slicing

In [63]:
a,a[1][1][1::,::-2]

(array([[[[201, 990, 702, 368, 249],
          [274,  67, 767, 540, 176],
          [174, 828, 712, 931, 337],
          [ 73, 555, 654, 741, 694],
          [ 40, 333, 964, 114, 428]],
 
         [[775, 521, 292, 625, 600],
          [802, 438, 759, 724, 244],
          [731, 179, 143, 410, 183],
          [866, 390, 214, 562, 506],
          [285, 865, 794, 148, 462]]],
 
 
        [[[973, 879, 410, 314, 609],
          [306, 962, 574, 528, 438],
          [531, 627, 236, 813, 320],
          [ 14,  30,  37, 738, 362],
          [985,  25, 910, 662, 512]],
 
         [[764,   8, 814, 513, 920],
          [754, 310, 189, 720, 666],
          [102, 945, 840, 482, 189],
          [503, 652, 720, 808, 974],
          [647, 265, 496, 334, 811]]]]),
 array([[666, 189, 754],
        [189, 840, 102],
        [974, 720, 503],
        [811, 496, 647]]))

In [64]:
a,a[1][1][1:,0:-2]

(array([[[[201, 990, 702, 368, 249],
          [274,  67, 767, 540, 176],
          [174, 828, 712, 931, 337],
          [ 73, 555, 654, 741, 694],
          [ 40, 333, 964, 114, 428]],
 
         [[775, 521, 292, 625, 600],
          [802, 438, 759, 724, 244],
          [731, 179, 143, 410, 183],
          [866, 390, 214, 562, 506],
          [285, 865, 794, 148, 462]]],
 
 
        [[[973, 879, 410, 314, 609],
          [306, 962, 574, 528, 438],
          [531, 627, 236, 813, 320],
          [ 14,  30,  37, 738, 362],
          [985,  25, 910, 662, 512]],
 
         [[764,   8, 814, 513, 920],
          [754, 310, 189, 720, 666],
          [102, 945, 840, 482, 189],
          [503, 652, 720, 808, 974],
          [647, 265, 496, 334, 811]]]]),
 array([[754, 310, 189],
        [102, 945, 840],
        [503, 652, 720],
        [647, 265, 496]]))

In [65]:
a[0,0,1:3,0:]

array([[274,  67, 767, 540, 176],
       [174, 828, 712, 931, 337]])

In [66]:
a[0][0][1:3,0:]

array([[274,  67, 767, 540, 176],
       [174, 828, 712, 931, 337]])

In [67]:
a,a[1][1][1:,0:-2]

(array([[[[201, 990, 702, 368, 249],
          [274,  67, 767, 540, 176],
          [174, 828, 712, 931, 337],
          [ 73, 555, 654, 741, 694],
          [ 40, 333, 964, 114, 428]],
 
         [[775, 521, 292, 625, 600],
          [802, 438, 759, 724, 244],
          [731, 179, 143, 410, 183],
          [866, 390, 214, 562, 506],
          [285, 865, 794, 148, 462]]],
 
 
        [[[973, 879, 410, 314, 609],
          [306, 962, 574, 528, 438],
          [531, 627, 236, 813, 320],
          [ 14,  30,  37, 738, 362],
          [985,  25, 910, 662, 512]],
 
         [[764,   8, 814, 513, 920],
          [754, 310, 189, 720, 666],
          [102, 945, 840, 482, 189],
          [503, 652, 720, 808, 974],
          [647, 265, 496, 334, 811]]]]),
 array([[754, 310, 189],
        [102, 945, 840],
        [503, 652, 720],
        [647, 265, 496]]))

## Extract Items

In [68]:
s_b=b[b>500]
s_b, type(s_b)

(array([], dtype=int32), numpy.ndarray)

In [69]:
s_a=a[a<500]
s_a,type(s_a)

(array([201, 368, 249, 274,  67, 176, 174, 337,  73,  40, 333, 114, 428,
        292, 438, 244, 179, 143, 410, 183, 390, 214, 285, 148, 462, 410,
        314, 306, 438, 236, 320,  14,  30,  37, 362,  25,   8, 310, 189,
        102, 482, 189, 265, 496, 334]),
 numpy.ndarray)

In [70]:

s_c=a[a%2==0]
s_c,a

(array([990, 702, 368, 274, 540, 176, 174, 828, 712, 654, 694,  40, 964,
        114, 428, 292, 600, 802, 438, 724, 244, 410, 866, 390, 214, 562,
        506, 794, 148, 462, 410, 314, 306, 962, 574, 528, 438, 236, 320,
         14,  30, 738, 362, 910, 662, 512, 764,   8, 814, 920, 754, 310,
        720, 666, 102, 840, 482, 652, 720, 808, 974, 496, 334]),
 array([[[[201, 990, 702, 368, 249],
          [274,  67, 767, 540, 176],
          [174, 828, 712, 931, 337],
          [ 73, 555, 654, 741, 694],
          [ 40, 333, 964, 114, 428]],
 
         [[775, 521, 292, 625, 600],
          [802, 438, 759, 724, 244],
          [731, 179, 143, 410, 183],
          [866, 390, 214, 562, 506],
          [285, 865, 794, 148, 462]]],
 
 
        [[[973, 879, 410, 314, 609],
          [306, 962, 574, 528, 438],
          [531, 627, 236, 813, 320],
          [ 14,  30,  37, 738, 362],
          [985,  25, 910, 662, 512]],
 
         [[764,   8, 814, 513, 920],
          [754, 310, 189, 720, 666],
  

#  Sorting, Adding elements
- v.sort(), np.sort(), np.concatenate()

In [71]:
# create array
a_sort=np.array([[22,11,10,9,33,3,20],[12,31,43,22,55,15,13]])
a_sort

array([[22, 11, 10,  9, 33,  3, 20],
       [12, 31, 43, 22, 55, 15, 13]])

In [72]:
# sort() - assending orders
a_sort.sort()
a_sort

array([[ 3,  9, 10, 11, 20, 22, 33],
       [12, 13, 15, 22, 31, 43, 55]])

In [73]:
a_sort=a_sort[::-1]   
a_sort

array([[12, 13, 15, 22, 31, 43, 55],
       [ 3,  9, 10, 11, 20, 22, 33]])

###### Quickly sort the numbers in assending order with:
- np.sort(v)

In [74]:
array=np.array([[[22,12,2,5,66,44,87,54],[22,12,2,5,66,44,87,54]],
                [[22,12,2,5,66,44,87,54],[22,12,2,5,66,44,87,54]]])
print(array)
# quickly sort the numbers in assending order with:
np.sort(array)

[[[22 12  2  5 66 44 87 54]
  [22 12  2  5 66 44 87 54]]

 [[22 12  2  5 66 44 87 54]
  [22 12  2  5 66 44 87 54]]]


array([[[ 2,  5, 12, 22, 44, 54, 66, 87],
        [ 2,  5, 12, 22, 44, 54, 66, 87]],

       [[ 2,  5, 12, 22, 44, 54, 66, 87],
        [ 2,  5, 12, 22, 44, 54, 66, 87]]])

##  in addition to sort
- v.argsort()- which is an indirect sort along  specified axis,
- np.lexsort(v), which is an indirect stable sort on multiple keys,
- searchsorted, which will find elements in a sorted array,
- partition, which is a partial sort.

In [75]:
a,a.argsort()

(array([[[[201, 990, 702, 368, 249],
          [274,  67, 767, 540, 176],
          [174, 828, 712, 931, 337],
          [ 73, 555, 654, 741, 694],
          [ 40, 333, 964, 114, 428]],
 
         [[775, 521, 292, 625, 600],
          [802, 438, 759, 724, 244],
          [731, 179, 143, 410, 183],
          [866, 390, 214, 562, 506],
          [285, 865, 794, 148, 462]]],
 
 
        [[[973, 879, 410, 314, 609],
          [306, 962, 574, 528, 438],
          [531, 627, 236, 813, 320],
          [ 14,  30,  37, 738, 362],
          [985,  25, 910, 662, 512]],
 
         [[764,   8, 814, 513, 920],
          [754, 310, 189, 720, 666],
          [102, 945, 840, 482, 189],
          [503, 652, 720, 808, 974],
          [647, 265, 496, 334, 811]]]]),
 array([[[[0, 4, 3, 2, 1],
          [1, 4, 0, 3, 2],
          [0, 4, 2, 1, 3],
          [0, 1, 2, 4, 3],
          [0, 3, 1, 4, 2]],
 
         [[2, 1, 4, 3, 0],
          [4, 1, 3, 2, 0],
          [2, 1, 4, 3, 0],
          [2, 1, 4, 3, 0]

In [76]:
# https://numpy.org/doc/stable/reference/generated/numpy.lexsort.html
#a=np.array([[[1,2,3,2,1],[65,4,3,2,3],[1,2,3,2,1],[65,4,3,2,3]],
#           [[1,2,98,2,90],[65,4,78,2,3],[1,2,3,2,1],[65,43,3,76,3]]])
a=np.array([[1,2,3,2,1,65,4,3,2,3]])
a.shape,a,np.lexsort(a),a.argsort()

((1, 10),
 array([[ 1,  2,  3,  2,  1, 65,  4,  3,  2,  3]]),
 array([0, 4, 1, 3, 8, 2, 7, 9, 6, 5], dtype=int64),
 array([[0, 4, 1, 3, 8, 2, 7, 9, 6, 5]], dtype=int64))

In [77]:
a.argmax()

5

In [78]:
a.argmin()

0

In [79]:
a[0][5],a[0][0]

(65, 1)

# 1) Operations on Array/Matrix

## Array operations¶

In [80]:
r1 =[[12,13,4],[15,16,1],[18,19,2],[21,2,24]]
a1 = np.asarray(r1)
a1

array([[12, 13,  4],
       [15, 16,  1],
       [18, 19,  2],
       [21,  2, 24]])

### Adding scalar value to each and every array value

In [81]:
a1+20

array([[32, 33, 24],
       [35, 36, 21],
       [38, 39, 22],
       [41, 22, 44]])

In [82]:
a1

array([[12, 13,  4],
       [15, 16,  1],
       [18, 19,  2],
       [21,  2, 24]])

#### Row wise addition

In [83]:
print(a1)
print('------------------')
a1+[[10],[15],[20],[25]]       # row

[[12 13  4]
 [15 16  1]
 [18 19  2]
 [21  2 24]]
------------------


array([[22, 23, 14],
       [30, 31, 16],
       [38, 39, 22],
       [46, 27, 49]])

In [84]:
print(a1)
a2 = a1+[[10],[15],[20],[25]]
a2

[[12 13  4]
 [15 16  1]
 [18 19  2]
 [21  2 24]]


array([[22, 23, 14],
       [30, 31, 16],
       [38, 39, 22],
       [46, 27, 49]])

### Column wise addition

In [85]:
print(a1)
a1+[10,15,20]

[[12 13  4]
 [15 16  1]
 [18 19  2]
 [21  2 24]]


array([[22, 28, 24],
       [25, 31, 21],
       [28, 34, 22],
       [31, 17, 44]])

### Adding array of same dimension

In [86]:
print(a1)
a1+[[2,3,4],
    [1,4,3],
    [2,1,3],
    [1,2,4]]

[[12 13  4]
 [15 16  1]
 [18 19  2]
 [21  2 24]]


array([[14, 16,  8],
       [16, 20,  4],
       [20, 20,  5],
       [22,  4, 28]])

# Broadcasting
- The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [87]:
a = np.array([[10,20,30],[40,50,60]])
print(a)
print('-------------')
b1 = 10
b2 = np.array([10])
c = np.array([10,10,10])
d = np.array([[10,10,10],[10,10,10]])
print('------------a*b1')
print(a*b1)
print('------------a*b2')
print(a*b2)
print('------------a*c')
print(a*c)
print('------------a*d')
print(a*d)

[[10 20 30]
 [40 50 60]]
-------------
------------a*b1
[[100 200 300]
 [400 500 600]]
------------a*b2
[[100 200 300]
 [400 500 600]]
------------a*c
[[100 200 300]
 [400 500 600]]
------------a*d
[[100 200 300]
 [400 500 600]]


## 2) Numpy array functions

### a) np.sum()

In [88]:
a1

array([[12, 13,  4],
       [15, 16,  1],
       [18, 19,  2],
       [21,  2, 24]])

In [89]:
a.sum()

210

In [90]:
np.sum(a1)

147

In [91]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [92]:
a.sum(axis=0)

array([50, 70, 90])

In [93]:
a.sum(axis=1)

array([ 60, 150])

### b) np.max() and np.min()

In [94]:
a,a.max(),a.min()

(array([[10, 20, 30],
        [40, 50, 60]]),
 60,
 10)

### c) np.argmax() and np.argmin()
- np.argmax() - Returns the indices of the maximum values along an axis

- np.argmin() - Returns the indices of the minimum values along an axis

In [95]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[11,12,3,4],[5,6,7,88]]])
a,a.argmax()

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[11, 12,  3,  4],
         [ 5,  6,  7, 88]]]),
 15)

In [96]:
a.argmin()

0

In [97]:
a.shape

(2, 2, 4)

In [98]:
p1=np.array([[11, 12,  3,  4],[ 5,  6,  7, 88]])
print(np.max(p1))
print(np.min(p1))
p1[1][3]

88
3


88

In [99]:
print(p1)
print(np.argmax(p1))
print(np.argmin(p1))

[[11 12  3  4]
 [ 5  6  7 88]]
7
2


In [100]:
p2=p1

In [101]:
print(np.argmax(p2,axis=0))  # column wise
print(np.argmin(p2,axis=0))  # column wise
print(np.argmax(p2,axis=1))  # row wise
print(np.argmin(p2,axis=1))  # row wise

[0 0 1 1]
[1 1 0 0]
[1 3]
[2 0]


### d) np.sort

In [102]:
p1

array([[11, 12,  3,  4],
       [ 5,  6,  7, 88]])

In [103]:
np.sort(p1)

array([[ 3,  4, 11, 12],
       [ 5,  6,  7, 88]])

In [104]:
p1[::-1],p1

(array([[ 5,  6,  7, 88],
        [11, 12,  3,  4]]),
 array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]))

In [105]:
# sort row wise 
np.sort(p1,axis=1)

array([[ 3,  4, 11, 12],
       [ 5,  6,  7, 88]])

In [106]:
np.sort(p1,axis=0)

array([[ 5,  6,  3,  4],
       [11, 12,  7, 88]])

### e) np.where() - returns index position for the matching conditions

In [107]:
p1,p1[np.where(p1%3==0)]

(array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]),
 array([12,  3,  6]))

In [108]:
np.where(p1 < 20)

(array([0, 0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2], dtype=int64))

In [109]:
np.where(p1 < 20,p1, p1*2),p1

(array([[ 11,  12,   3,   4],
        [  5,   6,   7, 176]]),
 array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]))

In [110]:
np.where(p1%2==0, p1+10, p1-7)

array([[ 4, 22, -4, 14],
       [-2, 16,  0, 98]])

In [111]:
np.where(p1%2==0),p1

((array([0, 0, 1, 1], dtype=int64), array([1, 3, 1, 3], dtype=int64)),
 array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]))

In [112]:
p1[np.where(p1%2==0)]

array([12,  4,  6, 88])

### f) np.extract() - directly returns the values on which conditions are applied,using the second parameter as array name

In [113]:
t1 = np.extract(p1>20, p1)
print(t1,p1)
type(t1)

[88] [[11 12  3  4]
 [ 5  6  7 88]]


numpy.ndarray

In [114]:
np.extract(p1%3!=0,p1)

array([11,  4,  5,  7, 88])

## g) np.insert() - adds values at specified position

In [115]:
np.insert(p1,2,41),p1

(array([11, 12, 41,  3,  4,  5,  6,  7, 88]),
 array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]))

## h) np.delete() - deletes values at specified position/index

In [116]:
p2 = np.delete(p1,4)
p2

array([11, 12,  3,  4,  6,  7, 88])

In [117]:
q1 = np.delete(p1,2,axis=1)  # deletes 2nd index column value corresponding to each row
print(q1)

[[11 12  4]
 [ 5  6 88]]


In [118]:
p1

array([[11, 12,  3,  4],
       [ 5,  6,  7, 88]])

In [119]:
q1 = np.delete(p1,1,axis=0) # deletes 2nd index row value corresponding to each column
print(q1)

[[11 12  3  4]]


## 3) Appending values ino array

In [120]:
np.append(p1,23)

array([11, 12,  3,  4,  5,  6,  7, 88, 23])

### a) Append/Add a new Row/Column

In [121]:
# Column wise - Add a value to each column, thereby creaing a new row
r2 = np.append(p1, [[13,14,15,16]], axis=0) 
print(r2)
print(r2.shape)

[[11 12  3  4]
 [ 5  6  7 88]
 [13 14 15 16]]
(3, 4)


In [122]:
p1,r2

(array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]),
 array([[11, 12,  3,  4],
        [ 5,  6,  7, 88],
        [13, 14, 15, 16]]))

In [123]:
# Row wise - Add a value to each row, thereby creaing a new column
r4 = np.append(p1, [[500],[600]], axis=1)
print(r4)
print(r4.shape)

[[ 11  12   3   4 500]
 [  5   6   7  88 600]]
(2, 5)


### 4) Iterating over numpy array - np.nditer()

In [124]:
for i in p1:
    print(i)

[11 12  3  4]
[ 5  6  7 88]


In [125]:
p1

array([[11, 12,  3,  4],
       [ 5,  6,  7, 88]])

In [126]:
for i in np.nditer(p1):
    print(i)

11
12
3
4
5
6
7
88


In [127]:
n1=np.arange(9).reshape(3,3)
n1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
# Add 0th column and 1st column
res1 = n1[:,0]+ n1[:,1]  # Element wise addition of 1st column and 2nd column
print(res1)
res2 = n1[:,0].sum() + n1[:,1].sum()  # Aggregate sum of all elements of 1st and 2nd column 
print(res2)
res3 = n1[0] + n1[1]  # sum of 0th and 1st row
print(res3)
res4 = n1[0].sum() + n1[1].sum() # Aggreate sum of 1st and 2nd row
print(res4)

[ 1  7 13]
21
[3 5 7]
15


In [129]:
for i in n1:
    print(i)

for i in np.nditer(n1):
    print(i,end=" ")

for i in n1:
    print(i,end=" ")

print(len(n1))
for i in range(len(n1)):
    print(n1[i],end=" ")

[0 1 2]
[3 4 5]
[6 7 8]
0 1 2 3 4 5 6 7 8 [0 1 2] [3 4 5] [6 7 8] 3
[0 1 2] [3 4 5] [6 7 8] 

In [130]:
n1.flatten()

for i in n1.flatten():
    print(i)

0
1
2
3
4
5
6
7
8


In [160]:
for i in np.nditer(n1):  
    print(i,end=' ')

for i in np.nditer(n1,order='C'):  # order= 'C', iterates element row wise
    print(i,end=' ')

print(n1)

for i in np.nditer(n1,order='F'):  # order= 'F', print element column wise
    print(i,end=' ')

print(n1)

for i in np.nditer(n1,order='A'):  # order= 'A', print element column wise
    print(i,end=' ')

for i in np.nditer(n1,order='K'):  # order= 'K', print element column wise
    print(i,end=' ')

print(n1)

0 1 2 3 4 5 6 7 8 0 1 2 3 4 5 6 7 8 [[0 1 2]
 [3 4 5]
 [6 7 8]]
0 3 6 1 4 7 2 5 8 [[0 1 2]
 [3 4 5]
 [6 7 8]]
0 1 2 3 4 5 6 7 8 0 1 2 3 4 5 6 7 8 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [132]:
n2=np.arange(9).reshape(3,3)
for x,y in np.nditer([n1,n2]): 
    print(x,y)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8


In [133]:
## 5) Matrix Multiplication and Transpose, Flatten

r1 = np.arange(2,20,2).reshape(3,3)
print(r1)  # Normal matrix

print(r1.T)  # Transpose of the array
print(r1.flatten())  # Flatten the normal array
print(r1.T.flatten())  # Flatten the transpose of the array

a1 = np.array([8,5,0,2,9,6,4,1,7]).reshape(3,3)
a2 = np.array([3,7,9,4,1,0,5,6,2]).reshape(3,3)
print(a1)
print(a2)

# Actual Matrix multiplication
r2 = np.matmul(a1,a2)
print(r2)

# Actual Matrix multiplication
r2 = np.dot(a1,a2)
print(r2)

print(a1)
print(a2)

# Element wise multiplication
r3 = np.multiply(a1,a2)
print(r3)

#<b>Linear algebra in NumPy:</b> 
#<br>The Linear Algebra module of NumPy offers various methods to apply linear algebra 
#on any numpy array. It can be used to determine:
#<ol>
#<li>rank, determinant, trace, etc. of an array.</li>
#<li>solve linear equations</li>
#</ol>

A = np.array([[0,1,2], 
              [2,3,4], 
              [1,2,5]],dtype=int) 
print(A)

print("Rank of A:", np.linalg.matrix_rank(A)) 
  
print("Trace of A:", np.trace(A))  # 0+3+5
  
print("Determinant of A:", np.linalg.det(A)) 
# 0(3*5-4*2) - 1(2*5 - 4*1) + 2(2*2 - 3*1)  = -6 + 2(1) = -6 + 2 = -4
  
print("Inverse of A:\n", np.linalg.inv(A)) 

### Solving Linear Equations using numpy

# Solving the equation:-
# x -2y = 8
# 3x + 4y = 18

a = np.array([[1, -2], [3, 4]]) 
b = np.array([8, 18]) 
  
print("Solution of linear equations:", np.linalg.solve(a, b))

# Solving the equation:-
# x +2y-z =9
# 2x -3y+7z = 15
# 7x -4y-5z = 13

a = np.array([[1, 2, -1], [2, -3, 7], [7, -4, -5]])
b = np.array([9,15,13])
x = np.linalg.solve(a, b)
print(x)

s1 = np.array([[0,1,2],[2,3,4],[0,2,1]])
print(s1)
print("Determinant of A:", np.linalg.det(s1)) 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[ 2  4  6  8 10 12 14 16 18]
[ 2  8 14  4 10 16  6 12 18]
[[8 5 0]
 [2 9 6]
 [4 1 7]]
[[3 7 9]
 [4 1 0]
 [5 6 2]]
[[44 61 72]
 [72 59 30]
 [51 71 50]]
[[44 61 72]
 [72 59 30]
 [51 71 50]]
[[8 5 0]
 [2 9 6]
 [4 1 7]]
[[3 7 9]
 [4 1 0]
 [5 6 2]]
[[24 35  0]
 [ 8  9  0]
 [20  6 14]]
[[0 1 2]
 [2 3 4]
 [1 2 5]]
Rank of A: 3
Trace of A: 8
Determinant of A: -4.0
Inverse of A:
 [[-1.75  0.25  0.5 ]
 [ 1.5   0.5  -1.  ]
 [-0.25 -0.25  0.5 ]]
Solution of linear equations: [ 6.8 -0.6]
[5. 3. 2.]
[[0 1 2]
 [2 3 4]
 [0 2 1]]
Determinant of A: 6.0


### Concatenation 

- np.concatenate(v1,v2)
- np.concatenate(v1,v2)
- np.concatenate((v1,v2),axis=0)
- np.concatenate((v1,v2),axis=1)

In [134]:
# creating two 1D array
arr_1=np.array([11,22,33,44,55])
arr_2=np.array([12,13,14,115,16])
print(arr)
arr_1,arr_2

[ 1 22 33 11 43 56  4]


(array([11, 22, 33, 44, 55]), array([ 12,  13,  14, 115,  16]))

In [135]:
arr_1+arr_2 

array([ 23,  35,  47, 159,  71])

In [136]:
arr_1_2=np.concatenate((arr_1,arr_2))  # use double paranthesis
arr_1_2

array([ 11,  22,  33,  44,  55,  12,  13,  14, 115,  16])

In [137]:
arr_2_1=np.concatenate((arr_2,arr_1),axis=0)  # use double paranthesis
arr_2_1

array([ 12,  13,  14, 115,  16,  11,  22,  33,  44,  55])

In [138]:
import random
a=np.random.randint(10,100,50).reshape(2,5,5)
a

array([[[48, 37, 11, 91, 78],
        [14, 23, 51, 69, 97],
        [85, 50, 58, 79, 53],
        [64, 36, 29, 32, 66],
        [94, 13, 92, 92, 20]],

       [[48, 69, 11, 77, 81],
        [72, 31, 72, 15, 56],
        [71, 70, 15, 90, 30],
        [62, 92, 43, 97, 35],
        [76, 76, 44, 15, 25]]])

In [139]:
b=np.random.randint(100,1000,50).reshape(2,5,5)
b

array([[[892, 320, 370, 674, 976],
        [699, 872, 970, 285, 409],
        [600, 396, 162, 185, 529],
        [772, 250, 491, 161, 419],
        [554, 244, 228, 119, 974]],

       [[440, 207, 296, 178, 136],
        [989, 435, 235, 725, 994],
        [674, 146, 698, 996, 434],
        [601, 558, 709, 721, 405],
        [100, 633, 131, 120, 825]]])

In [140]:
c_=np.concatenate((a,b)) # by defalt - # axis =0 rows wise horizontally
c_

array([[[ 48,  37,  11,  91,  78],
        [ 14,  23,  51,  69,  97],
        [ 85,  50,  58,  79,  53],
        [ 64,  36,  29,  32,  66],
        [ 94,  13,  92,  92,  20]],

       [[ 48,  69,  11,  77,  81],
        [ 72,  31,  72,  15,  56],
        [ 71,  70,  15,  90,  30],
        [ 62,  92,  43,  97,  35],
        [ 76,  76,  44,  15,  25]],

       [[892, 320, 370, 674, 976],
        [699, 872, 970, 285, 409],
        [600, 396, 162, 185, 529],
        [772, 250, 491, 161, 419],
        [554, 244, 228, 119, 974]],

       [[440, 207, 296, 178, 136],
        [989, 435, 235, 725, 994],
        [674, 146, 698, 996, 434],
        [601, 558, 709, 721, 405],
        [100, 633, 131, 120, 825]]])

In [141]:
d_=np.concatenate((b,a),axis=1)  # # axis =1 column wise vertically in numpy
d_

array([[[892, 320, 370, 674, 976],
        [699, 872, 970, 285, 409],
        [600, 396, 162, 185, 529],
        [772, 250, 491, 161, 419],
        [554, 244, 228, 119, 974],
        [ 48,  37,  11,  91,  78],
        [ 14,  23,  51,  69,  97],
        [ 85,  50,  58,  79,  53],
        [ 64,  36,  29,  32,  66],
        [ 94,  13,  92,  92,  20]],

       [[440, 207, 296, 178, 136],
        [989, 435, 235, 725, 994],
        [674, 146, 698, 996, 434],
        [601, 558, 709, 721, 405],
        [100, 633, 131, 120, 825],
        [ 48,  69,  11,  77,  81],
        [ 72,  31,  72,  15,  56],
        [ 71,  70,  15,  90,  30],
        [ 62,  92,  43,  97,  35],
        [ 76,  76,  44,  15,  25]]])

# Stack
- np.hstack((v1,v2))
- np.vstack((v1,v2))
- np.column_stack((v2,v1))

In [142]:
a=np.random.randint(100,1000,10).reshape(2,5)
b=np.random.randint(200,2000,10).reshape(2,5)
a,b

(array([[426, 271, 226, 624, 818],
        [183, 106, 275, 790, 750]]),
 array([[ 459,  509, 1206, 1880,  846],
        [ 560, 1000, 1486,  614, 1532]]))

In [143]:
np.stack((a,b))

array([[[ 426,  271,  226,  624,  818],
        [ 183,  106,  275,  790,  750]],

       [[ 459,  509, 1206, 1880,  846],
        [ 560, 1000, 1486,  614, 1532]]])

In [144]:
np.hstack((a,b))

array([[ 426,  271,  226,  624,  818,  459,  509, 1206, 1880,  846],
       [ 183,  106,  275,  790,  750,  560, 1000, 1486,  614, 1532]])

In [145]:
np.vstack((a,b))

array([[ 426,  271,  226,  624,  818],
       [ 183,  106,  275,  790,  750],
       [ 459,  509, 1206, 1880,  846],
       [ 560, 1000, 1486,  614, 1532]])

https://www.geeksforgeeks.org/numpy-stack-in-python/
https://www.geeksforgeeks.org/how-to-use-axis0-and-axis1-in-pandas/

In [146]:
np.stack((a,b),axis=0)

array([[[ 426,  271,  226,  624,  818],
        [ 183,  106,  275,  790,  750]],

       [[ 459,  509, 1206, 1880,  846],
        [ 560, 1000, 1486,  614, 1532]]])

In [147]:
np.stack((a,b),axis=1)

array([[[ 426,  271,  226,  624,  818],
        [ 459,  509, 1206, 1880,  846]],

       [[ 183,  106,  275,  790,  750],
        [ 560, 1000, 1486,  614, 1532]]])

In [148]:
np.stack((a,b),axis=2)

array([[[ 426,  459],
        [ 271,  509],
        [ 226, 1206],
        [ 624, 1880],
        [ 818,  846]],

       [[ 183,  560],
        [ 106, 1000],
        [ 275, 1486],
        [ 790,  614],
        [ 750, 1532]]])

In [149]:
np.stack((a,b),axis=2)

array([[[ 426,  459],
        [ 271,  509],
        [ 226, 1206],
        [ 624, 1880],
        [ 818,  846]],

       [[ 183,  560],
        [ 106, 1000],
        [ 275, 1486],
        [ 790,  614],
        [ 750, 1532]]])

# intersaction & difference
- np.intersect1d(n,n1)  # extract commen elements
- np.setdiff1d(n,n1)   # Unique value in given first variable

In [150]:
a=np.array([[[10,20,30,40,50],[60,70,80,90,100]],[[10,20,30,40,50],[60,70,80,90,100]]])
b=np.array([[[20,40,50],[60,70,80]],[[20,40,50],[60,70,80]]])
a,b

(array([[[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]],
 
        [[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]]]),
 array([[[20, 40, 50],
         [60, 70, 80]],
 
        [[20, 40, 50],
         [60, 70, 80]]]))

In [151]:
np.intersect1d(a,b)

array([20, 40, 50, 60, 70, 80])

In [152]:
np.setdiff1d(a,b)

array([ 10,  30,  90, 100])

# Numpy array copy vs View
- the difference between copy and view

In [153]:
a.shape,a

((2, 2, 5),
 array([[[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]],
 
        [[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]]]))

In [154]:
print(a)
a[1][1]=10    # a[set no][row no]= value
a

[[[ 10  20  30  40  50]
  [ 60  70  80  90 100]]

 [[ 10  20  30  40  50]
  [ 60  70  80  90 100]]]


array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]],

       [[ 10,  20,  30,  40,  50],
        [ 10,  10,  10,  10,  10]]])

In [155]:
a[0][1]=345
a

array([[[ 10,  20,  30,  40,  50],
        [345, 345, 345, 345, 345]],

       [[ 10,  20,  30,  40,  50],
        [ 10,  10,  10,  10,  10]]])

In [156]:
# view
v=a.view()
v
a[0][1]=876
a,v

(array([[[ 10,  20,  30,  40,  50],
         [876, 876, 876, 876, 876]],
 
        [[ 10,  20,  30,  40,  50],
         [ 10,  10,  10,  10,  10]]]),
 array([[[ 10,  20,  30,  40,  50],
         [876, 876, 876, 876, 876]],
 
        [[ 10,  20,  30,  40,  50],
         [ 10,  10,  10,  10,  10]]]))

In [157]:
# copy
c=a.copy()
c
a[1][1]=1000
c,a

(array([[[ 10,  20,  30,  40,  50],
         [876, 876, 876, 876, 876]],
 
        [[ 10,  20,  30,  40,  50],
         [ 10,  10,  10,  10,  10]]]),
 array([[[  10,   20,   30,   40,   50],
         [ 876,  876,  876,  876,  876]],
 
        [[  10,   20,   30,   40,   50],
         [1000, 1000, 1000, 1000, 1000]]]))